### PR TITLE
Correct handling of navigational status in RMC and GNS

### LINKED ISSUE #107: Fails to parse correct RMC sentence
As of version 1.5.0 and higher, I get the following when parsing data from my boat:

- Sentence: `$YDRMC,050700.00,A,5524.8683,N,01255.7938,E,0.2,181.3,230623,4.3,E,A,C*5F`
- Error: `nmea: YDRMC invalid navigation status: C`

### PR DESCRIPTION
**Pull request by calmh**
There was a misunderstanding on what the "navigation status" field should include. The enum values were for the "positioning system mode indicator" (variously "FAA mode" / "FFA mode" in this code) which is the preceding field. This changes the enum values to correspond to actual ones.

I realize that in principle this is a breaking change, however there's no such thing (as far as I can tell) as the previous navigational status values (as those are in fact mode values, which we don't keep an enum for), so I doubt anyone should depend on them... If they do, that will be a bug by itself and breaking it to highlight the error may be desirable.

Fixes #107

### CODE REVIEW

**Comment by aldas** [comment]
I think this change is OK (being author for this problem).  In some sense current API is/was (completely) broken - rendering these sentences useless in some situations.

@icholy what you think, you have stronger opinions.

**Comment by icholy** [comment]
@aldas if you're ok with it then I'm ok with it.

**Comment by aldas** [comment]
maybe we could add some ability to switch `Parser.EnumString/EnumChars` to be more lenient with unknown values in another PR. In case %$%^ hits the fan. NMEA0183 spec being closed and we actually can not guarantee 100% that we have correct enums or some manufacturer do not have their "idea" of correct values.

**Review by aldas — APPROVED** [review]
so far this seemed to work because "S" (old `NavStatusSimulated` and new  `NavStatusSafe`) and "V" (old `NavStatusDataValid` and new  `NavStatusNotValid`) from old and new enum  collide and these are most used values.  Probably this was the reason this was not found before. RMC is very common sentence.

If anyone depend on these enums and this change breaks their build - this is probably better than silently fail in production parsing uncommon values.

File: types.go [hunk 1]
```diff
@@ -127,20 +127,14 @@ const (
...
-	// NavStatusEstimated is Estimated (dead-reckoning) mode
-	NavStatusEstimated = "E"
-	// NavStatusManualInput is Manual Input Mode
-	NavStatusManualInput = "M"
-	// NavStatusSimulated is Simulated Mode
-	NavStatusSimulated = "S"
-	// NavStatusDataNotValid is Data Not Valid
-	NavStatusDataNotValid = "N"
-	// NavStatusDataValid is valid
-	NavStatusDataValid = "V"
```
Comment (aldas) [inline types.go:143]: I propose deleting all but these 2 and mark these deprecated

```go
	// NavStatusSimulated is Simulated Mode
	// Deprecated: correct is NavStatusSafe
	NavStatusSimulated = "S"
	// NavStatusDataValid is valid
	// Deprecated: correct is NavStatusNotValid
	NavStatusDataValid = "V"
```

in that case when someone depend most used values - we do not break their apps immediately but when you depend incorrect enums - we force you to fix your code (replace deleted values)

**Review by aldas — CHANGES_REQUESTED** [review]

File: types.go (hunk 1 above)
Comment (icholy) [reply types.go:143]: That makes sense

Comment (icholy) [reply types.go:143]: The deprecation message should be 

```
Deprecated: use NavStatusNotValid
```

**Comment by calmh** [comment]
Thanks, I added back the relevant constants with some commentary.

**Review by aldas — APPROVED** [review]
LGTM

**Comment by gytisgreitai** [comment]
This was not released for some reason? v1.8.0 is latest with  Feb 4, 2023  ?
